behaviors:
  MoveToGoal:
    trainer_type: ppo
    hyperparameters:
      batch_size: 128
      buffer_size: 4096
      learning_rate: 2.5e-4
      beta: 4.0e-4
      epsilon: 0.2
      lambd: 0.99
      num_epoch: 5
      learning_rate_schedule: linear
      beta_schedule: constant
      epsilon_schedule: linear
    network_settings:
      normalize: true
      hidden_units: 256
      num_layers: 2
    reward_signals:
      extrinsic:
        gamma: 0.99
        strength: 1.0
      gail:
        strength: 0.5
        demo_path: Demos/GolfPakkuDemo.demo
    behavioral_cloning:
        strength: 0.5
        demo_path: Demos/GolfPakkuDemo.demo
    max_steps: 5000000
    time_horizon: 128
    summary_freq: 1000